(- 5 4)
(Y -_ 5 4)
(-_ (Y -_) 5 4)
((fn [f m s] (zero? s m (f (pred m) (pred s)))) (Y -_) 5 4)
(Y -_ 4 3)
(-_ (Y -_) 4 3)
((fn [f m s] (zero? s m (f (pred m) (pred s)))) (Y -_) 4 3)
(Y -_ 3 2)
(-_ (Y -_) 3 2)
((fn [f m s] (zero? s m (f (pred m) (pred s)))) (Y -_) 3 2)
(Y -_ 2 1)
(-_ (Y -_) 2 1)
((fn [f m s] (zero? s m (f (pred m) (pred s)))) (Y -_) 2 1)
(Y -_ 1 0)
(-_ (Y -_) 1 0)
((fn [f m s] (zero? s m (f (pred m) (pred s)))) (Y -_) 1 0)
1
