(- 5 4)
((Y -_) 5 4)
(-_ (Y -_) 5 4)
((fn [f m s] ((zero? s) m (f (pred m) (pred s)))) (Y -_) 5 4)
((fn [m s] ((zero? s) m ((Y -_) (pred m) (pred s)))) 5 4)
((fn [s] ((zero? s) 5 ((Y -_) (pred 5) (pred s)))) 4)
((zero? 4) 5 ((Y -_) (pred 5) (pred 4)))
(false 5 ((Y -_) (pred 5) (pred 4)))
((Y -_) (pred 5) (pred 4))
(-_ (Y -_) (pred 5) (pred 4))
((fn [f m s] ((zero? s) m (f (pred m) (pred s)))) (Y -_) (pred 5) (pred 4))
((fn [m s] ((zero? s) m ((Y -_) (pred m) (pred s)))) (pred 5) (pred 4))
((fn [s] ((zero? s) (pred 5) ((Y -_) (pred (pred 5)) (pred s)))) (pred 4))
((zero? (pred 4)) (pred 5) ((Y -_) (pred (pred 5)) (pred (pred 4))))
((zero? 3) (pred 5) ((Y -_) (pred (pred 5)) (pred (pred 4))))
(false (pred 5) ((Y -_) (pred (pred 5)) (pred (pred 4))))
((Y -_) (pred (pred 5)) (pred (pred 4)))
(-_ (Y -_) (pred (pred 5)) (pred (pred 4)))
((fn [f m s] ((zero? s) m (f (pred m) (pred s)))) (Y -_) (pred (pred 5)) (pred (pred 4)))
((fn [m s] ((zero? s) m ((Y -_) (pred m) (pred s)))) (pred (pred 5)) (pred (pred 4)))
((fn [s] ((zero? s) (pred (pred 5)) ((Y -_) (pred (pred (pred 5))) (pred s)))) (pred (pred 4)))
((zero? (pred (pred 4))) (pred (pred 5)) ((Y -_) (pred (pred (pred 5))) (pred (pred (pred 4)))))
((zero? (pred 3)) (pred (pred 5)) ((Y -_) (pred (pred (pred 5))) (pred (pred (pred 4)))))
((zero? 2) (pred (pred 5)) ((Y -_) (pred (pred (pred 5))) (pred (pred (pred 4)))))
(false (pred (pred 5)) ((Y -_) (pred (pred (pred 5))) (pred (pred (pred 4)))))
((Y -_) (pred (pred (pred 5))) (pred (pred (pred 4))))
(-_ (Y -_) (pred (pred (pred 5))) (pred (pred (pred 4))))
((fn [f m s] ((zero? s) m (f (pred m) (pred s)))) (Y -_) (pred (pred (pred 5))) (pred (pred (pred 4))))
((fn [m s] ((zero? s) m ((Y -_) (pred m) (pred s)))) (pred (pred (pred 5))) (pred (pred (pred 4))))
((fn [s] ((zero? s) (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred s)))) (pred (pred (pred 4))))
((zero? (pred (pred (pred 4)))) (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4))))))
((zero? (pred (pred 3))) (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4))))))
((zero? (pred 2)) (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4))))))
((zero? 1) (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4))))))
(false (pred (pred (pred 5))) ((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4))))))
((Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4)))))
(-_ (Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4)))))
((fn [f m s] ((zero? s) m (f (pred m) (pred s)))) (Y -_) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4)))))
((fn [m s] ((zero? s) m ((Y -_) (pred m) (pred s)))) (pred (pred (pred (pred 5)))) (pred (pred (pred (pred 4)))))
((fn [s] ((zero? s) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred s)))) (pred (pred (pred (pred 4)))))
((zero? (pred (pred (pred (pred 4))))) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
((zero? (pred (pred (pred 3)))) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
((zero? (pred (pred 2))) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
((zero? (pred 1)) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
((zero? 0) (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
(true (pred (pred (pred (pred 5)))) ((Y -_) (pred (pred (pred (pred (pred 5))))) (pred (pred (pred (pred (pred 4)))))))
(pred (pred (pred (pred 5))))
(pred (pred (pred 4)))
(pred (pred 3))
(pred 2)
1
