(ack 2 1)
(Y ack_ 2 1)
(ack_ (Y ack_) 2 1)
((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 2 1)
(Y ack_ 1 (Y ack_ 2 0))
(ack_ (Y ack_) 1 (Y ack_ 2 0))
((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 (Y ack_ 2 0))
(zero? (Y ack_ 2 0) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (ack_ (Y ack_) 2 0) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 2 0) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (Y ack_ 1 1) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (ack_ (Y ack_) 1 1) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 1) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (Y ack_ 0 (Y ack_ 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (ack_ (Y ack_) 0 (Y ack_ 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 (Y ack_ 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 (ack_ (Y ack_) 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 (Y ack_ 0 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 (ack_ (Y ack_) 0 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(zero? (+ 1 2) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0)))))
(Y ack_ 0 (Y ack_ 1 (pred (Y ack_ 2 0))))
(ack_ (Y ack_) 0 (Y ack_ 1 (pred (Y ack_ 2 0))))
((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 (pred (Y ack_ 2 0))))
(+ 1 (Y ack_ 1 (pred (Y ack_ 2 0))))
(+ 1 (ack_ (Y ack_) 1 (pred (Y ack_ 2 0))))
(+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 (pred (Y ack_ 2 0))))
(+ 1 (zero? (pred (Y ack_ 2 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (ack_ (Y ack_) 2 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 2 0)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (Y ack_ 1 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (ack_ (Y ack_) 1 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 1)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (Y ack_ 0 (Y ack_ 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (ack_ (Y ack_) 0 (Y ack_ 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 (Y ack_ 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 (ack_ (Y ack_) 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 (Y ack_ 0 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 (ack_ (Y ack_) 0 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (zero? (pred (+ 1 2)) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0)))))))
(+ 1 (Y ack_ 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 (ack_ (Y ack_) 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 (+ 1 (Y ack_ 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 (+ 1 (ack_ (Y ack_) 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 (pred (pred (Y ack_ 2 0))))))
(+ 1 (+ 1 (zero? (pred (pred (Y ack_ 2 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (ack_ (Y ack_) 2 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 2 0))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (Y ack_ 1 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (ack_ (Y ack_) 1 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 1))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (Y ack_ 0 (Y ack_ 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (ack_ (Y ack_) 0 (Y ack_ 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 (Y ack_ 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 (ack_ (Y ack_) 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 (Y ack_ 0 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 (ack_ (Y ack_) 0 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (zero? (pred (pred (+ 1 2))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0)))))))))
(+ 1 (+ 1 (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 (ack_ (Y ack_) 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 (+ 1 (Y ack_ 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 (+ 1 (ack_ (Y ack_) 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 (pred (pred (pred (Y ack_ 2 0))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (Y ack_ 2 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (ack_ (Y ack_) 2 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 2 0)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (Y ack_ 1 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (ack_ (Y ack_) 1 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 1)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (Y ack_ 0 (Y ack_ 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (ack_ (Y ack_) 0 (Y ack_ 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 (Y ack_ 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 (Y ack_ 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 (ack_ (Y ack_) 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 1 0))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 (Y ack_ 0 1))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 (ack_ (Y ack_) 0 1))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 1))))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (zero? (pred (pred (pred (+ 1 2)))) (Y ack_ 0 1) (Y ack_ 0 (Y ack_ 1 (pred (pred (pred (pred (Y ack_ 2 0)))))))))))
(+ 1 (+ 1 (+ 1 (Y ack_ 0 1))))
(+ 1 (+ 1 (+ 1 (ack_ (Y ack_) 0 1))))
(+ 1 (+ 1 (+ 1 ((fn [f m n] (zero? m (+ 1 n) (zero? n (f (pred m) 1) (f (pred m) (f m (pred n)))))) (Y ack_) 0 1))))
(+ 1 (+ 1 (+ 1 2)))
5
