(fact 0)
((Y fact_) 0)
(((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) 0)
(((fn [x] (x x)) (fn [x] (fact_ (x x)))) 0)
(((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) 0)
((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) 0)
(((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] ((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (x x))) (fn [x] ((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (x x))))) 0)
((fn [n] ((zero? n) 1 (* n (((fn [x] ((fn [f n1] ((zero? n1) 1 (* n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 (* n1 (f (pred n1))))) (x x)))) (pred n))))) 0)
((zero? 0) 1 (* 0 (((fn [x] ((fn [f n1] ((zero? n1) 1 (* n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 (* n1 (f (pred n1))))) (x x)))) (pred 0))))
(((fn [n] (n (K false) true)) 0) 1 ((fn [m n] (fn [f1 x1] (m (n f1) x1))) 0 (((fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f1 x1] (m (n f1) x1))) n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f1 x1] (m (n f1) x1))) n1 (f (pred n1))))) (x x)))) (pred 0))))
((0 (K false) true) 1 ((fn [n] (fn [f1 x1] (0 (n f1) x1))) (((fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f1 x1] (m (n f1) x1))) n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f1 x1] (m (n f1) x1))) n1 (f (pred n1))))) (x x)))) (pred 0))))
(((fn [f x] x) (K false) true) 1 (fn [f1 x1] (0 ((((fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f2 x2] (m (n f2) x2))) n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f2 x2] (m (n f2) x2))) n1 (f (pred n1))))) (x x)))) (pred 0)) f1) x1)))
(((fn [x] x) true) 1 (fn [f1 x1] ((fn [f3 x3] x3) ((((fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f2 x2] (m (n f2) x2))) n1 (f (pred n1))))) (x x))) (fn [x] ((fn [f n1] ((zero? n1) 1 ((fn [m n] (fn [f2 x2] (m (n f2) x2))) n1 (f (pred n1))))) (x x)))) (pred (fn [f3 x3] x3))) f1) x1)))
(true 1 (fn [f1 x1] ((fn [x3] x3) x1)))
((fn [a b] a) 1 (fn [f1 x1] ((fn [x3] x3) x1)))
((fn [b] 1) (fn [f1 x1] ((fn [x3] x3) x1)))
1
