(fact 2)
(Y fact_ 2)
(fact_ (Y fact_) 2)
((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 2)
(zero? 2 1 (* 2 (Y fact_ (pred 2))))
(* 2 (Y fact_ (pred 2)))
(* 2 (fact_ (Y fact_) (pred 2)))
(* 2 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) (pred 2)))
(* 2 (zero? (pred 2) 1 (* (pred 2) (Y fact_ (pred (pred 2))))))
(* 2 (zero? 1 1 (* (pred 2) (Y fact_ (pred (pred 2))))))
(* 2 (* (pred 2) (Y fact_ (pred (pred 2)))))
(* 2 (* 1 (Y fact_ (pred (pred 2)))))
(* 2 (* 1 (fact_ (Y fact_) (pred (pred 2)))))
(* 2 (* 1 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) (pred (pred 2)))))
(* 2 (* 1 (zero? (pred (pred 2)) 1 (* (pred (pred 2)) (Y fact_ (pred (pred (pred 2))))))))
(* 2 (* 1 (zero? (pred 1) 1 (* (pred (pred 2)) (Y fact_ (pred (pred (pred 2))))))))
(* 2 (* 1 (zero? 0 1 (* (pred (pred 2)) (Y fact_ (pred (pred (pred 2))))))))
(* 2 (* 1 1))
(* 2 1)
2
