(fact 3)
(Y fact_ 3)
(fact_ (Y fact_) 3)
((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 3)
(* 3 (Y fact_ 2))
(* 3 (fact_ (Y fact_) 2))
(* 3 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 2))
(* 3 (* 2 (Y fact_ 1)))
(* 3 (* 2 (fact_ (Y fact_) 1)))
(* 3 (* 2 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 1)))
(* 3 (* 2 (* 1 (Y fact_ 0))))
(* 3 (* 2 (* 1 (fact_ (Y fact_) 0))))
(* 3 (* 2 (* 1 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 0))))
(* 3 (* 2 (* 1 1)))
6
