(fact 2)
((Y fact_) 2)
(((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) 2)
(((fn [x] (x x)) (fn [x] (fact_ (x x)))) 2)
(((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) 2)
((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) 2)
(((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) 2)
(((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (Y fact_)) 2)
((fn [n] ((zero? n) 1 (* n ((Y fact_) (pred n))))) 2)
((zero? 2) 1 (* 2 ((Y fact_) (pred 2))))
(((fn [n] (n (K false) true)) 2) 1 (* 2 ((Y fact_) (pred 2))))
((2 (K false) true) 1 (* 2 ((Y fact_) (pred 2))))
(((fn [f x] (f (f x))) (K false) true) 1 (* 2 ((Y fact_) (pred 2))))
(((fn [x] ((K false) ((K false) x))) true) 1 (* 2 ((Y fact_) (pred 2))))
(((K false) ((K false) true)) 1 (* 2 ((Y fact_) (pred 2))))
((((fn [x] (fn [u] x)) false) ((K false) true)) 1 (* 2 ((Y fact_) (pred 2))))
(((fn [u] false) ((K false) true)) 1 (* 2 ((Y fact_) (pred 2))))
(false 1 (* 2 ((Y fact_) (pred 2))))
(* 2 ((Y fact_) (pred 2)))
((fn [m n] (fn [f x] (m (n f) x))) 2 ((Y fact_) (pred 2)))
((fn [n] (fn [f x] (2 (n f) x))) ((Y fact_) (pred 2)))
(fn [f x] (2 (((Y fact_) (pred 2)) f) x))
(fn [f x] ((fn [f x] (f (f x))) (((Y fact_) (pred 2)) f) x))
(fn [f x] ((fn [x] ((((Y fact_) (pred 2)) f) ((((Y fact_) (pred 2)) f) x))) x))
(fn [f x] ((((Y fact_) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] (x x)) (fn [x] (fact_ (x x)))) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (Y fact_)) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fn [n] ((zero? n) 1 (* n ((Y fact_) (pred n))))) (pred 2)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((zero? (pred 2)) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [n] (n (K false) true)) (pred 2)) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((pred 2) (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((1 (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f x] (f x)) (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] ((K false) x)) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [x] (fn [u] x)) false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [u] false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((false 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((* (pred 2) ((Y fact_) (pred (pred 2)))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fn [m n] (fn [f x] (m (n f) x))) (pred 2) ((Y fact_) (pred (pred 2)))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fn [n] (fn [f x] ((pred 2) (n f) x))) ((Y fact_) (pred (pred 2)))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((fn [f x] ((pred 2) (((Y fact_) (pred (pred 2))) f) x)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((fn [x] ((pred 2) (((Y fact_) (pred (pred 2))) f) x)) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((pred 2) (((Y fact_) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (1 (((Y fact_) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((fn [f x] (f x)) (((Y fact_) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((fn [x] ((((Y fact_) (pred (pred 2))) f) x)) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((Y fact_) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] (x x)) (fn [x] (fact_ (x x)))) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (Y fact_)) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((fn [n] ((zero? n) 1 (* n ((Y fact_) (pred n))))) (pred (pred 2))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((zero? (pred (pred 2))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [n] (n (K false) true)) (pred (pred 2))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((pred (pred 2)) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [n] (fn [f x] (extract (n (inc f) (K x))))) (pred 2)) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [f x] (extract ((pred 2) (inc f) (K x)))) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [x] (extract ((pred 2) (inc (K false)) (K x)))) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((extract ((pred 2) (inc (K false)) (K true))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [k] (k I)) ((pred 2) (inc (K false)) (K true))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((pred 2) (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((1 (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [f x] (f x)) (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [x] ((inc (K false)) x)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((((fn [f] (fn [g h] (h (g f)))) (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [g h] (h (g (K false)))) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [h] (h ((K true) (K false)))) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((I ((K true) (K false))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((K true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((((((fn [x] (fn [u] x)) true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((((fn [u] true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((true 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((1 f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (((fn [f x] (f x)) f) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] ((fn [x] (f x)) ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (f ((((Y fact_) (pred 2)) f) x)))
(fn [f x] (f (((((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) (pred 2)) f) x)))
(fn [f x] (f (((((fn [x] (x x)) (fn [x] (fact_ (x x)))) (pred 2)) f) x)))
(fn [f x] (f (((((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) (pred 2)) f) x)))
(fn [f x] (f ((((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred 2)) f) x)))
(fn [f x] (f (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred 2)) f) x)))
(fn [f x] (f (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (Y fact_)) (pred 2)) f) x)))
(fn [f x] (f ((((fn [n] ((zero? n) 1 (* n ((Y fact_) (pred n))))) (pred 2)) f) x)))
(fn [f x] (f ((((zero? (pred 2)) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((fn [n] (n (K false) true)) (pred 2)) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((pred 2) (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f ((((1 (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((fn [f x] (f x)) (K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((fn [x] ((K false) x)) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((K false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f ((((((fn [x] (fn [u] x)) false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((((fn [u] false) true) 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((false 1 (* (pred 2) ((Y fact_) (pred (pred 2))))) f) x)))
(fn [f x] (f (((* (pred 2) ((Y fact_) (pred (pred 2)))) f) x)))
(fn [f x] (f ((((fn [m n] (fn [f x] (m (n f) x))) (pred 2) ((Y fact_) (pred (pred 2)))) f) x)))
(fn [f x] (f ((((fn [n] (fn [f x] ((pred 2) (n f) x))) ((Y fact_) (pred (pred 2)))) f) x)))
(fn [f x] (f (((fn [f x] ((pred 2) (((Y fact_) (pred (pred 2))) f) x)) f) x)))
(fn [f x] (f ((fn [x] ((pred 2) (((Y fact_) (pred (pred 2))) f) x)) x)))
(fn [f x] (f ((pred 2) (((Y fact_) (pred (pred 2))) f) x)))
(fn [f x] (f (1 (((Y fact_) (pred (pred 2))) f) x)))
(fn [f x] (f ((fn [f x] (f x)) (((Y fact_) (pred (pred 2))) f) x)))
(fn [f x] (f ((fn [x] ((((Y fact_) (pred (pred 2))) f) x)) x)))
(fn [f x] (f ((((Y fact_) (pred (pred 2))) f) x)))
(fn [f x] (f (((((fn [f] ((fn [x] (x x)) (fn [x] (f (x x))))) fact_) (pred (pred 2))) f) x)))
(fn [f x] (f (((((fn [x] (x x)) (fn [x] (fact_ (x x)))) (pred (pred 2))) f) x)))
(fn [f x] (f (((((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x)))) (pred (pred 2))) f) x)))
(fn [f x] (f ((((fact_ ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred (pred 2))) f) x)))
(fn [f x] (f (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) ((fn [x] (fact_ (x x))) (fn [x] (fact_ (x x))))) (pred (pred 2))) f) x)))
(fn [f x] (f (((((fn [f n] ((zero? n) 1 (* n (f (pred n))))) (Y fact_)) (pred (pred 2))) f) x)))
(fn [f x] (f ((((fn [n] ((zero? n) 1 (* n ((Y fact_) (pred n))))) (pred (pred 2))) f) x)))
(fn [f x] (f ((((zero? (pred (pred 2))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [n] (n (K false) true)) (pred (pred 2))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((pred (pred 2)) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((fn [n] (fn [f x] (extract (n (inc f) (K x))))) (pred 2)) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [f x] (extract ((pred 2) (inc f) (K x)))) (K false) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [x] (extract ((pred 2) (inc (K false)) (K x)))) true) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((extract ((pred 2) (inc (K false)) (K true))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [k] (k I)) ((pred 2) (inc (K false)) (K true))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((pred 2) (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((1 (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((fn [f x] (f x)) (inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((fn [x] ((inc (K false)) x)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((inc (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((((fn [f] (fn [g h] (h (g f)))) (K false)) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((fn [g h] (h (g (K false)))) (K true)) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [h] (h ((K true) (K false)))) I) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((I ((K true) (K false))) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((K true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((((((fn [x] (fn [u] x)) true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((((fn [u] true) (K false)) 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f (((true 1 (* (pred (pred 2)) ((Y fact_) (pred (pred (pred 2)))))) f) x)))
(fn [f x] (f ((1 f) x)))
(fn [f x] (f (((fn [f x] (f x)) f) x)))
(fn [f x] (f ((fn [x] (f x)) x)))
(fn [f x] (f (f x)))
