(fact 4)
(Y fact_ 4)
(fact_ (Y fact_) 4)
((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 4)
(* 4 (Y fact_ 3))
(* 4 (fact_ (Y fact_) 3))
(* 4 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 3))
(* 4 (* 3 (Y fact_ 2)))
(* 4 (* 3 (fact_ (Y fact_) 2)))
(* 4 (* 3 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 2)))
(* 4 (* 3 (* 2 (Y fact_ 1))))
(* 4 (* 3 (* 2 (fact_ (Y fact_) 1))))
(* 4 (* 3 (* 2 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 1))))
(* 4 (* 3 (* 2 (* 1 (Y fact_ 0)))))
(* 4 (* 3 (* 2 (* 1 (fact_ (Y fact_) 0)))))
(* 4 (* 3 (* 2 (* 1 ((fn [f n] (zero? n 1 (* n (f (pred n))))) (Y fact_) 0)))))
(* 4 (* 3 (* 2 (* 1 1))))
24
